TASK1:
  name: COCOEETaggerDel
  type: Tagger
  loss: CrossEntropyLoss
  task_id: 1
  dataroot: datasets
  features_h5path1: ''
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 32
  max_region_num: 37
  batch_size: 32
  train_split: train
  val_split: val
  test_split: test
  lr: 0.00002
  num_epoch: 20
  tagger_class: 2
TASK2:
  name: COCOEETaggerAdd
  type: Tagger
  loss: CrossEntropyLoss
  task_id: 2
  dataroot: datasets
  features_h5path1: ''
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 32
  max_region_num: 37
  batch_size: 32
  train_split: train
  val_split: val
  test_split: test
  lr: 0.00002
  num_epoch: 20
  tagger_class: 2
TASK3:
  name: COCOEEInserter
  type: Inserter
  loss: CrossEntropyLoss
  task_id: 3
  dataroot: datasets
  features_h5path1: ''
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 32
  max_region_num: 37
  batch_size: 32
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
  tagger_class: 2
TASK4:
  name: Flickr30KEETaggerDel
  type: Tagger
  loss: CrossEntropyLoss
  task_id: 4
  dataroot: datasets
  features_h5path1: ''
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 32
  max_region_num: 37
  batch_size: 32
  train_split: train
  val_split: val
  test_split: test
  lr: 0.00002
  num_epoch: 20
  tagger_class: 2
TASK5:
  name: Flickr30KEETaggerAdd
  type: Tagger
  loss: CrossEntropyLoss
  task_id: 5
  dataroot: datasets
  features_h5path1: ''
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 32
  max_region_num: 37
  batch_size: 32
  train_split: train
  val_split: val
  test_split: test
  lr: 0.00002
  num_epoch: 20
  tagger_class: 2
TASK6:
  name: Flickr30KEEInserter
  type: Inserter
  loss: CrossEntropyLoss
  task_id: 6
  dataroot: datasets
  features_h5path1: ''
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 32
  max_region_num: 37
  batch_size: 32
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
  tagger_class: 2
